# "org" ensures this Service is used with the correct Serverless Framework License Key.
org: juanfix
# "service" is the name of this project. This will also be added to your AWS resource names.
service: lambda-debt-capacity

useDotenv: true

plugins:
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: .env
    REGION: ${env:REGION}

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:REGION}
  environment:
    REGION: ${env:REGION}
    QUEUE_SQS_EMAIL_SENDER_ARN: ${env:QUEUE_SQS_EMAIL_SENDER_ARN}
    QUEUE_SQS_EMAIL_SENDER_URL: ${env:QUEUE_SQS_EMAIL_SENDER_URL}
    QUEUE_DEBT_CAPACITY_ARN: ${env:QUEUE_DEBT_CAPACITY_ARN}
    QUEUE_DEBT_CAPACITY_URL: ${env:QUEUE_DEBT_CAPACITY_URL}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - ${env:QUEUE_SQS_EMAIL_SENDER_ARN}
        - ${env:QUEUE_DEBT_CAPACITY_ARN}

functions:
  debtCapacity:
    handler: src/handler.debtCapacity
    events:
      - httpApi:
          path: /api/v1/calcular-capacidad
          method: post
